/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3AY9ohbsTgu
 */
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";

export function EventRegistration() {
  return (
    <div className="mx-auto max-w-2xl mt-[50px] space-y-6">
      <div className="space-y-2 text-center">
        <h1 className="text-3xl font-bold">Register for Event</h1>
        <p className="text-gray-500 dark:text-gray-400">Enter your information to register for the event</p>
      </div>
      <div className="space-y-4">
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label htmlFor="team-name">Team Name</Label>
            <Input id="team-name" placeholder="Team Name" required />
          </div>
          <div className="space-y-2">
            <Label htmlFor="level">Level</Label>
            <Select>
              <SelectTrigger id="level">
                <SelectValue placeholder="Select" />
              </SelectTrigger>
              <SelectContent position="popper">
                <SelectItem value="Bachelors">Bachelors</SelectItem>
                <SelectItem value="Intermediate">Intermediate</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
        <div className="space-y-2">
          <Label htmlFor="faculty">Faculty</Label>
          <Select>
            <SelectTrigger id="faculty">
              <SelectValue placeholder="Select" />
            </SelectTrigger>
            <SelectContent position="popper">
              <SelectItem value="CSIT">CSIT</SelectItem>
              <SelectItem value="BCA">BCA</SelectItem>
              <SelectItem value="BIT">BIT</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div className="space-y-2">
          <Label htmlFor="semester">Semester/Class</Label>
          <Select>
            <SelectTrigger id="semester">
              <SelectValue placeholder="Select" />
            </SelectTrigger>
            <SelectContent position="popper">
              <SelectItem value="1">1</SelectItem>
              <SelectItem value="2">2</SelectItem>
              <SelectItem value="3">3</SelectItem>
              <SelectItem value="4">4</SelectItem>
              <SelectItem value="5">5</SelectItem>
              <SelectItem value="6">6</SelectItem>
              <SelectItem value="7">7</SelectItem>
              <SelectItem value="8">8</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div className="space-y-2">
          <Label htmlFor="project-name">Project Name</Label>
          <Input id="project-name" placeholder="Project Name" required />
        </div>
        <div className="space-y-2">
          <Label htmlFor="email">Email</Label>
          <Input id="email" placeholder="m@example.com" required type="email" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="captain-name">Captain Name</Label>
          <Input id="captain-name" placeholder="Captain Name" required />
        </div>
        <div className="space-y-2">
          <Label htmlFor="members">Members</Label>
          <div className="grid grid-cols-2 gap-4">
            <Input id="member-1" placeholder="Member 1" required />
            <Input id="member-2" placeholder="Member 2" required />
            <Input id="member-3" placeholder="Member 3" required />
            <Input id="member-4" placeholder="Member 4" required />
            <Input id="member-5" placeholder="Member 5" required />
            <Input id="member-6" placeholder="Member 6" required />
          </div>
        </div>
        <div className="space-y-2">
          <Label htmlFor="description">Description</Label>
          <Textarea className="min-h-[100px]" id="description" placeholder="Description" required />
        </div>
        <Button className="w-full" type="submit">
          Register
        </Button>
      </div>
    </div>
  );
}
