/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/8vEUadkEcp2
 */
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { Button } from "@/components/ui/button"

export default function Dashboard() {
  return (
    <div className="w-full min-h-screen p-6">
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-2xl font-bold">Teams Dashboard</h1>
      </div>
      <div className="border shadow-sm rounded-lg">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Team Name</TableHead>
              <TableHead>Level</TableHead>
              <TableHead>Faculty</TableHead>
              <TableHead>Semester</TableHead>
              <TableHead>Project Name</TableHead>
              <TableHead>Email</TableHead>
              <TableHead>Captain Name</TableHead>
              <TableHead>Members</TableHead>
              <TableHead>Description</TableHead>
              <TableHead>Action</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow>
              <TableCell>Team Alpha</TableCell>
              <TableCell>Intermediate</TableCell>
              <TableCell>Computer Science</TableCell>
              <TableCell>3</TableCell>
              <TableCell>Project X</TableCell>
              <TableCell>alpha@university.com</TableCell>
              <TableCell>John Doe</TableCell>
              <TableCell>5</TableCell>
              <TableCell>Working on AI-based solutions</TableCell>
              <TableCell>
                <Button size="sm" variant="outline">
                  View Details
                </Button>
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell>Team Beta</TableCell>
              <TableCell>Advanced</TableCell>
              <TableCell>Information Technology</TableCell>
              <TableCell>4</TableCell>
              <TableCell>Project Y</TableCell>
              <TableCell>beta@university.com</TableCell>
              <TableCell>Jane Doe</TableCell>
              <TableCell>6</TableCell>
              <TableCell>Developing cloud-based applications</TableCell>
              <TableCell>
                <Button size="sm" variant="outline">
                  View Details
                </Button>
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell>Team Gamma</TableCell>
              <TableCell>Beginner</TableCell>
              <TableCell>Software Engineering</TableCell>
              <TableCell>2</TableCell>
              <TableCell>Project Z</TableCell>
              <TableCell>gamma@university.com</TableCell>
              <TableCell>Richard Roe</TableCell>
              <TableCell>4</TableCell>
              <TableCell>Creating web applications</TableCell>
              <TableCell>
                <Button size="sm" variant="outline">
                  View Details
                </Button>
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </div>
    </div>
  )
}
